<?php

require __DIR__ . '/core.php';
define('APP_DIR', __DIR__);
define('DB', APP_DIR . '/../db/app.db');

class MyController extends Controller
{
    public function index()
    {
        $this->_set([
            'author' => 'Hiroki Teranishi',
            'message' => 'Hello World!',
        ]);
        $this->_render(APP_DIR . '/templates/index.php');
    }

    public function posts()
    {
        $model = new Post();
        $messages = $model->find();
        $this->_set(compact('messages'));
        $this->_render(APP_DIR . '/templates/posts.php');
    }
}

class Post
{
    public function find()
    {
        $posts = [];
        try {
            $pdo = new PDO('sqlite:' . DB);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
            $stmt = $pdo->query("SELECT * FROM message WHERE status=1 ORDER BY id DESC");
            $posts = $stmt->fetchAll();
        } catch (Exception $e) {
            echo $e->getMessage();
        }
        return $posts;
    }
}

function execute() {
    try {
        $app = new App();
        $app->get('/', 'My:index');             // routing '/' to MyController::index action
        $app->get('/posts', 'My:posts');        // routing '/posts' to MyController::posts action
        $app->get('/about', function() {        // routing '/about' to a callback function
            echo '<a href="https://github.com/chantera" target="_blank">See my GitHub page.</a>';
        });
        $app->error(404, 'error404');           // routing 404 error to a function by name
        $app->run();
    } catch (Exception $e) {
        echo $e->getMessage();
        echo $e->getTraceAsString();
    }
}

function error404($request) {
    ?>
    <h1>Not Found</h1>
    <p>The requested URL <?= $request->path ?> was not found on this server.</p>
    <hr>
    <p>This is generated by myblog app.</p>
    <?php
}

function h($string) {
    return htmlspecialchars($string);
}
